import { NextRequest, NextResponse } from "next/server";
import { db } from "@/db";
import { responseTemplates } from "@/db/schema";
import { getAdminSession } from "@/lib/auth";
import { writeAudit } from "@/lib/audit";
import { eq } from "drizzle-orm";

export async function GET(){ return NextResponse.json({templates:await db.select().from(responseTemplates).where(eq(responseTemplates.isActive,true))}); }
export async function POST(req:NextRequest){const s=await getAdminSession();if(!s||!["super_admin","district_admin","reviewer"].includes(s.role))return NextResponse.json({error:"Forbidden"},{status:403});try{const b=await req.json();const [r]=await db.insert(responseTemplates).values({name:String(b.name||"").trim(),category:b.category||null,bodyEn:String(b.bodyEn||"").trim(),bodyUr:b.bodyUr||null,createdBy:s.id}).returning();await writeAudit(s,"template_create","response_template",r.id,r.name);return NextResponse.json({template:r},{status:201});}catch{return NextResponse.json({error:"Unable to create template"},{status:400});}}
export async function PATCH(req:NextRequest){const s=await getAdminSession();if(!s||!["super_admin","district_admin","reviewer"].includes(s.role))return NextResponse.json({error:"Forbidden"},{status:403});try{const b=await req.json();const id=String(b.id||"");const [before]=await db.select().from(responseTemplates).where(eq(responseTemplates.id,id)).limit(1);if(!before)return NextResponse.json({error:"Not found"},{status:404});const [r]=await db.update(responseTemplates).set({name:b.name??before.name,category:b.category??before.category,bodyEn:b.bodyEn??before.bodyEn,bodyUr:b.bodyUr??before.bodyUr,isActive:b.isActive??before.isActive,updatedAt:new Date()}).where(eq(responseTemplates.id,id)).returning();await writeAudit(s,"template_update","response_template",id,r.name,before,r);return NextResponse.json({template:r});}catch{return NextResponse.json({error:"Unable to update template"},{status:400});}}
export async function DELETE(req:NextRequest){const s=await getAdminSession();if(!s||s.role!=="super_admin")return NextResponse.json({error:"Forbidden"},{status:403});const id=new URL(req.url).searchParams.get("id");if(!id)return NextResponse.json({error:"id required"},{status:400});await db.update(responseTemplates).set({isActive:false,updatedAt:new Date()}).where(eq(responseTemplates.id,id));await writeAudit(s,"template_disable","response_template",id);return NextResponse.json({success:true});}